name: ci-golang-worflow
on: [pull_request]
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Da checkout, busca os dados da branch pra dentro do ubuntu
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - run: go test
      - run: go run math.go
